version: '3.8'

services:

  mysql:
    image: mysql:8.0.22
    container_name: mysql_comics
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: comics
      MYSQL_PASSWORD: comics
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comics_db

  jaeger:
    image: jaegertracing/all-in-one:1.24
    container_name: jaeger_comics
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus_comics
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:7.5.10
    container_name: grafana_comics
    ports:
      - 3000:3000